name: CI Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver chromium-browser
          # Periksa apakah chromedriver sudah ter-link dengan benar,
          # jika tidak, buat symbolic link
          if [ "$(readlink -f /usr/bin/chromedriver)" != "/usr/lib/chromium-browser/chromedriver" ]; then
            sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          else
            echo "Chromedriver sudah ter-link dengan benar."
          fi

      - name: Run Selenium Tests
        run: python test_app.py
